# Generated by Django 6.0.4 on 2026-04-21 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('export_scope', models.CharField(default='master', max_length=80)),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('completed', 'Completed'), ('failed', 'Failed')], default='preview', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('critical_errors', models.PositiveIntegerField(default=0)),
                ('warnings', models.PositiveIntegerField(default=0)),
                ('preview_payload', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_label', models.CharField(max_length=120)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='reports.businessunit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subchannels', to='reports.channel')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('name', 'business_unit')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='reports.businessunit')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('name', 'business_unit')},
            },
        ),
        migrations.CreateModel(
            name='MetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.CharField(max_length=100, unique=True)),
                ('subchannel', models.CharField(blank=True, max_length=120)),
                ('campaign_type', models.CharField(blank=True, choices=[('Meta Ads', 'Meta Ads'), ('Google Ads', 'Google Ads'), ('TikTok Ads', 'TikTok Ads'), ('Comfama Uva', 'Comfama Uva'), ('Rappi Ads', 'Rappi Ads'), ('Falabella Ads', 'Falabella Ads'), ('Mercado Libre Ads', 'Mercado Libre Ads'), ('WhatsApp Campaigns', 'WhatsApp Campaigns'), ('Sellerchat', 'Sellerchat')], max_length=40)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('period_type', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=10)),
                ('period_label', models.CharField(max_length=120)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('metric_name', models.CharField(choices=[('sales_total', 'Ventas totales'), ('sales_month', 'Ventas del mes'), ('sales_whatsapp', 'Ventas por WhatsApp'), ('sales_web', 'Ventas web'), ('sales_marketplace', 'Ventas marketplace'), ('investment', 'Inversion'), ('ad_spend', 'Gasto de pauta'), ('ad_spend_by_country', 'Gasto de pauta por pais'), ('investment_by_product', 'Inversion por producto'), ('cpa', 'CPA'), ('cpa_weekly', 'CPA semanal'), ('cpa_monthly', 'CPA mensual'), ('cpa_by_product', 'CPA por producto'), ('cpl', 'CPL'), ('cpl_weekly', 'CPL semanal'), ('cpl_monthly', 'CPL mensual'), ('cpl_by_campaign', 'CPL por campana'), ('roas', 'ROAS'), ('messages', 'Mensajes'), ('clicks', 'Clicks'), ('purchases', 'Compras'), ('closed_deals', 'Negocios cerrados'), ('conversion_rate', 'Porcentaje de conversion'), ('close_rate', 'Close rate'), ('average_ticket', 'Ticket promedio'), ('orders', 'Ordenes'), ('units', 'Unidades'), ('utility', 'Utilidad'), ('operational_profit', 'Utilidad operativa')], max_length=40)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('value_origin', models.CharField(choices=[('imported', 'Importado'), ('calculated', 'Calculado')], default='imported', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_records', to='reports.businessunit')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_records', to='reports.channel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_records', to='reports.country')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_records', to='reports.product')),
            ],
            options={
                'ordering': ['-date_start', 'business_unit__display_order', 'channel__display_order', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('sale_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('shipping_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=80)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='reports.businessunit')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transactions', to='reports.channel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transactions', to='reports.country')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transactions', to='reports.product')),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Ecommerce', 'Ecommerce'), ('Pauta', 'Pauta'), ('Marketplace', 'Marketplace'), ('Chat Web Bali', 'Chat Web Bali')], max_length=30)),
                ('task_name', models.TextField()),
                ('responsible', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('Completado', 'Completado'), ('En proceso', 'En proceso'), ('Pendiente', 'Pendiente'), ('Bloqueado', 'Bloqueado')], max_length=20)),
                ('priority', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reports.weeklyreport')),
            ],
            options={
                'ordering': ['area', '-priority', 'status', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('week_label', models.CharField(max_length=120)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('area', models.CharField(choices=[('Ecommerce', 'Ecommerce'), ('Pauta', 'Pauta'), ('Marketplace', 'Marketplace'), ('Chat Web Bali', 'Chat - Web Bali'), ('Tecnico', 'Tecnico'), ('Operativo', 'Operativo')], max_length=20)),
                ('task_name', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('completed', 'Completada'), ('blocked', 'Bloqueada')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], max_length=20)),
                ('task_type', models.CharField(choices=[('operativa', 'Operativa'), ('estrategica', 'Estrategica'), ('correctiva', 'Correctiva'), ('preventiva', 'Preventiva'), ('incidencia', 'Incidencia'), ('optimizacion', 'Optimizacion')], max_length=20)),
                ('impact', models.CharField(choices=[('ventas', 'Ventas'), ('conversion', 'Conversion'), ('operacion', 'Operacion'), ('tecnologia', 'Tecnologia'), ('rentabilidad', 'Rentabilidad'), ('experiencia_cliente', 'Experiencia cliente'), ('riesgo', 'Riesgo')], max_length=30)),
                ('result', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment_ref', models.CharField(blank=True, max_length=120)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_tasks', to='reports.businessunit')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_tasks', to='reports.channel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_tasks', to='reports.country')),
                ('related_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='reports.metricrecord')),
            ],
            options={
                'ordering': ['-date_start', '-priority', 'status', 'area', 'task_id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_ref', models.CharField(max_length=120, unique=True)),
                ('period_label', models.CharField(blank=True, max_length=120)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('presentation', 'Presentacion'), ('image', 'Imagen'), ('excel', 'Excel'), ('document', 'Documento')], max_length=20)),
                ('uploaded_file', models.FileField(blank=True, upload_to='attachments/%Y/%m/')),
                ('file_path_or_url', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='reports.businessunit')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='reports.channel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='reports.country')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='reports.weeklytask')),
            ],
            options={
                'ordering': ['-created_at', 'file_name'],
            },
        ),
        migrations.AddIndex(
            model_name='metricrecord',
            index=models.Index(fields=['period_type', 'date_start', 'date_end'], name='reports_met_period__8bad69_idx'),
        ),
        migrations.AddIndex(
            model_name='metricrecord',
            index=models.Index(fields=['business_unit', 'channel', 'country'], name='reports_met_busines_8f3869_idx'),
        ),
        migrations.AddIndex(
            model_name='metricrecord',
            index=models.Index(fields=['metric_name', 'period_label'], name='reports_met_metric__2d1e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='metricrecord',
            index=models.Index(fields=['campaign_type', 'value_origin'], name='reports_met_campaig_dcb33f_idx'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['sale_date', 'country', 'channel'], name='reports_sal_sale_da_d9e4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['business_unit', 'sale_date'], name='reports_sal_busines_d5280d_idx'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.UniqueConstraint(fields=('source_file', 'source_sheet', 'source_row'), name='reports_sale_source_row_unique'),
        ),
        migrations.AddIndex(
            model_name='weeklytask',
            index=models.Index(fields=['date_start', 'date_end'], name='reports_wee_date_st_9d0bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklytask',
            index=models.Index(fields=['business_unit', 'channel', 'country'], name='reports_wee_busines_0d0ece_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklytask',
            index=models.Index(fields=['status', 'priority', 'impact'], name='reports_wee_status_d02fd8_idx'),
        ),
    ]
