# Generated by Django 6.0.4 on 2026-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessunit",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="channel",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="logo",
            field=models.FileField(blank=True, upload_to="channel_logos/"),
        ),
    ]
