# Generated by Django 6.0.4 on 2026-04-22 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_job_titles(apps, schema_editor):
    UserProfile = apps.get_model("reports", "UserProfile")
    JobTitle = apps.get_model("reports", "JobTitle")

    for profile in UserProfile.objects.exclude(job_title="").exclude(job_title__isnull=True):
        role, _ = JobTitle.objects.get_or_create(name=profile.job_title, defaults={"is_active": True})
        profile.role = role
        profile.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_businessunit_description_channel_description_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("is_leadership_role", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgendaTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(verbose_name="fecha de finalizacion")),
                ("reminder_at", models.DateTimeField(blank=True, null=True, verbose_name="fecha de recordatorio")),
                ("reminder_enabled", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pendiente"), ("in_progress", "En proceso"), ("completed", "Completada"), ("canceled", "Cancelada")], default="pending", max_length=20)),
                ("assigned_to", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agenda_assigned_tasks", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agenda_created_tasks", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Agenda",
                "verbose_name_plural": "Agenda",
                "ordering": ["status", "due_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["assigned_to", "status", "due_at"], name="reports_agen_assigne_1c4f72_idx"),
                    models.Index(fields=["reminder_enabled", "reminder_at"], name="reports_agen_reminde_374d2f_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="country",
            name="business_units",
            field=models.ManyToManyField(blank=True, related_name="countries", to="reports.businessunit"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="manager",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="direct_reports", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="user_profiles", to="reports.jobtitle"),
        ),
        migrations.RunPython(migrate_existing_job_titles, migrations.RunPython.noop),
    ]
