# Generated by Django 6.0.4 on 2026-04-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_jobtitle_agendatask_country_assignments_user_hierarchy"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChannelSale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sale_date", models.DateField()),
                ("sales_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("source_type", models.CharField(choices=[("manual", "Manual"), ("imported", "Importado")], default="manual", max_length=20)),
                ("source_file", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("business_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_channel_sales", to="reports.businessunit")),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_channel_sales", to="reports.channel")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_channel_sales", to="reports.country")),
            ],
            options={
                "verbose_name": "Venta diaria web",
                "verbose_name_plural": "Ventas diarias web",
                "ordering": ["-sale_date", "business_unit__display_order", "country__display_order"],
                "indexes": [
                    models.Index(fields=["sale_date", "business_unit", "country", "channel"], name="reports_dai_sale_da_c07067_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("business_unit", "country", "channel", "sale_date"), name="reports_daily_channel_sale_unique"),
                ],
            },
        ),
    ]
