# Generated by Django 6.0.4 on 2026-04-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_dailychannelsale"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdPlatform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Fuente de pauta",
                "verbose_name_plural": "Fuentes de pauta",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyAdSpend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("spend_date", models.DateField()),
                ("spend_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("source_type", models.CharField(choices=[("manual", "Manual"), ("imported", "Importado")], default="manual", max_length=20)),
                ("source_file", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("ad_platform", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_spends", to="reports.adplatform")),
                ("business_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_ad_spends", to="reports.businessunit")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_ad_spends", to="reports.country")),
            ],
            options={
                "verbose_name": "Inversion diaria",
                "verbose_name_plural": "Inversiones diarias",
                "ordering": ["-spend_date", "business_unit__display_order", "country__display_order", "ad_platform__name"],
                "indexes": [
                    models.Index(fields=["spend_date", "business_unit", "country", "ad_platform"], name="reports_dai_spend_d8b9a4_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("business_unit", "country", "ad_platform", "spend_date"), name="reports_daily_ad_spend_unique"),
                ],
            },
        ),
    ]
