# Generated by Django 6.0.4 on 2026-04-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Canal', 'verbose_name_plural': 'Canales'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='dailychannelsale',
            options={'ordering': ['-sale_date', 'business_unit__display_order', 'country__display_order'], 'verbose_name': 'Venta diaria', 'verbose_name_plural': 'Ventas diarias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameIndex(
            model_name='agendatask',
            new_name='reports_age_assigne_b968cd_idx',
            old_name='reports_agen_assigne_1c4f72_idx',
        ),
        migrations.RenameIndex(
            model_name='agendatask',
            new_name='reports_age_reminde_547eea_idx',
            old_name='reports_agen_reminde_374d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyadspend',
            new_name='reports_dai_spend_d_d8157e_idx',
            old_name='reports_dai_spend_d8b9a4_idx',
        ),
        migrations.RenameIndex(
            model_name='dailychannelsale',
            new_name='reports_dai_sale_da_fed9c6_idx',
            old_name='reports_dai_sale_da_c07067_idx',
        ),
    ]
