# Generated by Django 6.0.4 on 2026-04-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_dailyproductcategorymetric'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('business_unit__isnull', False)), fields=('business_unit', 'slug'), name='reports_channel_unit_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('business_unit__isnull', True)), fields=('slug',), name='reports_channel_global_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='dailyadspend',
            constraint=models.CheckConstraint(condition=models.Q(('spend_amount__gte', 0)), name='reports_daily_ad_spend_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailychannelsale',
            constraint=models.CheckConstraint(condition=models.Q(('sales_amount__gte', 0)), name='reports_daily_channel_sale_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailychannelsale',
            constraint=models.CheckConstraint(condition=models.Q(('order_count__gte', 0)), name='reports_daily_channel_sale_orders_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductcategorymetric',
            constraint=models.CheckConstraint(condition=models.Q(('cpa_meta__isnull', True), ('cpa_meta__gte', 0), _connector='OR'), name='reports_category_metric_cpa_meta_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductcategorymetric',
            constraint=models.CheckConstraint(condition=models.Q(('cpa_google__isnull', True), ('cpa_google__gte', 0), _connector='OR'), name='reports_category_metric_cpa_google_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductcategorymetric',
            constraint=models.CheckConstraint(condition=models.Q(('spend_meta__gte', 0)), name='reports_category_metric_spend_meta_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductcategorymetric',
            constraint=models.CheckConstraint(condition=models.Q(('spend_google__gte', 0)), name='reports_category_metric_spend_google_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductcategorymetric',
            constraint=models.CheckConstraint(condition=models.Q(('total_spend__gte', 0)), name='reports_category_metric_total_spend_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductcategorymetric',
            constraint=models.CheckConstraint(condition=models.Q(('sales_amount__gte', 0)), name='reports_category_metric_sales_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='metricrecord',
            constraint=models.CheckConstraint(condition=models.Q(('date_start__lte', models.F('date_end'))), name='reports_metric_record_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='metricrecord',
            constraint=models.CheckConstraint(condition=models.Q(('metric_value__gte', 0)), name='reports_metric_record_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('business_unit__isnull', False)), fields=('business_unit', 'slug'), name='reports_product_unit_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('business_unit__isnull', True)), fields=('slug',), name='reports_product_global_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='reports_sale_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('sale_value__gte', 0)), name='reports_sale_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_value__gte', 0)), name='reports_sale_shipping_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='weeklytask',
            constraint=models.CheckConstraint(condition=models.Q(('date_start__lte', models.F('date_end'))), name='reports_weekly_task_valid_date_range'),
        ),
    ]
