# Generated by Django 6.0.4 on 2026-04-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_channel_reports_channel_unit_slug_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductCategorySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField()),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Importado')], default='imported', max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_category_sales', to='reports.businessunit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_channel_sales', to='reports.productcategory')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_category_sales', to='reports.channel')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_category_sales', to='reports.country')),
            ],
            options={
                'verbose_name': 'Venta diaria por categoria y canal',
                'verbose_name_plural': 'Ventas diarias por categoria y canal',
                'ordering': ['-sale_date', 'category__name', 'channel__display_order'],
                'indexes': [models.Index(fields=['sale_date', 'business_unit', 'country', 'channel', 'category'], name='reports_cat_sale_date_dims_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_unit', 'country', 'channel', 'category', 'sale_date'), name='reports_daily_product_category_sale_unique'), models.CheckConstraint(condition=models.Q(('sales_amount__gte', 0)), name='reports_daily_product_category_sale_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='reports_daily_product_category_sale_qty_nonnegative')],
            },
        ),
    ]
