# Generated by Django 6.0.4 on 2026-04-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_dailyproductcategorysale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfamaProductReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('price_tariff_a', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('price_tariff_b', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_inferred', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comfama_references', to='reports.productcategory')),
            ],
            options={
                'verbose_name': 'Referencia Comfama',
                'verbose_name_plural': 'Referencias Comfama',
                'ordering': ['category__name', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='ComfamaSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField()),
                ('tariff', models.CharField(choices=[('T-A', 'Tarifa A'), ('T-B', 'Tarifa B')], max_length=10)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='reports.comfamaproductreference')),
            ],
            options={
                'verbose_name': 'Venta Uva Comfama',
                'verbose_name_plural': 'Ventas Uva Comfama',
                'ordering': ['-sale_date', 'reference__category__name', 'reference__reference'],
            },
        ),
        migrations.CreateModel(
            name='ComfamaAdMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField()),
                ('cpl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('spend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('conversations', models.PositiveIntegerField(default=0)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comfama_ad_metrics', to='reports.productcategory')),
            ],
            options={
                'verbose_name': 'Pauta Uva Comfama',
                'verbose_name_plural': 'Pauta Uva Comfama',
                'ordering': ['-metric_date', 'category__name'],
                'indexes': [models.Index(fields=['metric_date', 'category'], name='rep_comf_ad_date_cat_idx')],
                'constraints': [models.UniqueConstraint(fields=('metric_date', 'category'), name='reports_comfama_ad_metric_unique'), models.CheckConstraint(condition=models.Q(('cpl__gte', 0)), name='reports_comfama_ad_cpl_nonnegative'), models.CheckConstraint(condition=models.Q(('spend_amount__gte', 0)), name='reports_comfama_ad_spend_nonnegative'), models.CheckConstraint(condition=models.Q(('conversations__gte', 0)), name='reports_comfama_ad_conversations_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='comfamaproductreference',
            constraint=models.CheckConstraint(condition=models.Q(('price_tariff_a__gte', 0)), name='reports_comfama_ref_price_a_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='comfamaproductreference',
            constraint=models.CheckConstraint(condition=models.Q(('price_tariff_b__gte', 0)), name='reports_comfama_ref_price_b_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='comfamasale',
            index=models.Index(fields=['sale_date', 'tariff'], name='rep_comf_sale_date_tariff_idx'),
        ),
        migrations.AddConstraint(
            model_name='comfamasale',
            constraint=models.UniqueConstraint(condition=models.Q(('source_file', ''), _negated=True), fields=('source_file', 'source_row'), name='reports_comfama_sale_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='comfamasale',
            constraint=models.CheckConstraint(condition=models.Q(('sales_amount__gte', 0)), name='reports_comfama_sale_amount_nonnegative'),
        ),
    ]
