# Generated by Django 6.0.4 on 2026-04-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_comfamaproductreference_comfamasale_comfamaadmetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductcategorysale',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailyproductcategorysale',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailyproductcategorysale',
            name='original_currency',
            field=models.CharField(default='COP', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='dailyproductcategorysale',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gte', 0)), name='reports_daily_product_category_sale_original_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductcategorysale',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gte', 0)), name='reports_daily_product_category_sale_fx_nonnegative'),
        ),
    ]
