# Generated by Django 6.0.4 on 2026-04-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_seed_comfama_uva_ad_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaliWhatsAppSale',
            fields=[
            ],
            options={
                'verbose_name': 'WhatsApp Bali',
                'verbose_name_plural': 'WhatsApp Bali',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.dailychannelsale',),
        ),
        migrations.CreateModel(
            name='BaliDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField()),
                ('visits', models.PositiveIntegerField(default=0)),
                ('web_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('web_order_count', models.PositiveIntegerField(default=0)),
                ('google_spend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('google_attributed_orders', models.PositiveIntegerField(default=0)),
                ('whatsapp_conversations', models.PositiveIntegerField(default=0)),
                ('cpa', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Importado')], default='manual', max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bali_daily_metrics', to='reports.businessunit')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bali_daily_metrics', to='reports.country')),
            ],
            options={
                'verbose_name': 'Metrica diaria Bali',
                'verbose_name_plural': 'Metricas diarias Bali',
                'ordering': ['-metric_date'],
                'indexes': [models.Index(fields=['metric_date', 'business_unit', 'country'], name='reports_bali_metric_d_bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_unit', 'country', 'metric_date'), name='reports_bali_daily_metric_unique'), models.CheckConstraint(condition=models.Q(('visits__gte', 0)), name='reports_bali_daily_visits_nonnegative'), models.CheckConstraint(condition=models.Q(('web_sales_amount__gte', 0)), name='reports_bali_daily_sales_nonnegative'), models.CheckConstraint(condition=models.Q(('web_order_count__gte', 0)), name='reports_bali_daily_orders_nonnegative'), models.CheckConstraint(condition=models.Q(('google_spend_amount__gte', 0)), name='reports_bali_daily_spend_nonnegative'), models.CheckConstraint(condition=models.Q(('google_attributed_orders__gte', 0)), name='reports_bali_daily_google_orders_nonnegative'), models.CheckConstraint(condition=models.Q(('whatsapp_conversations__gte', 0)), name='reports_bali_daily_conversations_nonnegative'), models.CheckConstraint(condition=models.Q(('cpa__gte', 0)), name='reports_bali_daily_cpa_nonnegative')],
            },
        ),
    ]
