# Generated by Django 6.0.4 on 2026-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_remove_elixir_distrisex_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychannelsale',
            name='spend_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailychannelsale',
            name='units',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
