# Generated by Codex on 2026-04-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0024_dailychannelsale_spend_amount_dailychannelsale_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("business_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_targets", to="reports.businessunit")),
                ("channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sales_targets", to="reports.channel")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_targets", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Meta de venta",
                "verbose_name_plural": "Metas de venta",
                "ordering": ["-date_start", "user__username", "channel__display_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="salestarget",
            constraint=models.CheckConstraint(condition=models.Q(("date_start__lte", models.F("date_end"))), name="reports_sales_target_valid_date_range"),
        ),
        migrations.AddConstraint(
            model_name="salestarget",
            constraint=models.CheckConstraint(condition=models.Q(("target_amount__gte", 0)), name="reports_sales_target_amount_nonnegative"),
        ),
        migrations.AddIndex(
            model_name="salestarget",
            index=models.Index(fields=["user", "business_unit", "channel", "date_start", "date_end"], name="reports_sales_target_dims_idx"),
        ),
    ]
