# Generated by Codex on 2026-04-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0025_salestarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceSale",
            fields=[],
            options={
                "verbose_name": "Ventas Marketplace",
                "verbose_name_plural": "Ventas Marketplace",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.dailychannelsale",),
        ),
    ]
