# Generated by Codex on 2026-04-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0026_marketplacesale_proxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalGoalTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180, verbose_name="tarea")),
                ("description", models.TextField(blank=True, verbose_name="instrucciones")),
                ("due_date", models.DateField(blank=True, null=True, verbose_name="fecha limite")),
                ("status", models.CharField(choices=[("pending", "Pendiente"), ("in_progress", "En proceso"), ("completed", "Completada")], default="pending", max_length=20, verbose_name="estado")),
                ("employee_response", models.TextField(blank=True, verbose_name="comentarios o enlaces del empleado")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assigned_operational_goal_tasks", to=settings.AUTH_USER_MODEL)),
                ("assigned_to", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operational_goal_tasks", to=settings.AUTH_USER_MODEL)),
                ("sales_target", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operational_tasks", to="reports.salestarget", verbose_name="meta")),
            ],
            options={
                "verbose_name": "Meta operativa",
                "verbose_name_plural": "Metas operativas",
                "ordering": ["status", "due_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="operationalgoaltask",
            index=models.Index(fields=["assigned_to", "status", "due_date"], name="reports_oper_task_user_idx"),
        ),
        migrations.AddIndex(
            model_name="operationalgoaltask",
            index=models.Index(fields=["assigned_by", "status"], name="reports_oper_task_mgr_idx"),
        ),
    ]
