# Generated by Codex on 2026-04-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0027_operationalgoaltask"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalGoalTaskAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="operational_tasks/%Y/%m/")),
                ("label", models.CharField(blank=True, max_length=160)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="reports.operationalgoaltask")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operational_task_attachments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Adjunto de meta operativa",
                "verbose_name_plural": "Adjuntos de metas operativas",
                "ordering": ["-created_at"],
            },
        ),
    ]
