# Generated by Django 6.0.4 on 2026-05-06 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_katerine_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha de cumplimiento')),
                ('registered_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='horas registradas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('completed', 'Realizada'), ('canceled', 'Cancelada')], default='pending', max_length=20, verbose_name='estado')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='asignada a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='user_tasks/%Y/%m/', verbose_name='archivo')),
                ('label', models.CharField(blank=True, max_length=160, verbose_name='etiqueta')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.usertask')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de tarea',
                'verbose_name_plural': 'Adjuntos de tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['assigned_to', 'status', 'due_date'], name='reports_user_task_user_idx'),
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['created_by', 'status', 'due_date'], name='reports_user_task_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.CheckConstraint(condition=models.Q(('registered_hours__gte', 0)), name='reports_user_task_hours_nonnegative'),
        ),
    ]
