# Generated by Django 6.0.4 on 2026-05-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_usertask_usertaskattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='links',
            field=models.TextField(blank=True, help_text='Un enlace por linea.', verbose_name='enlaces'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='asignada a'),
        ),
        migrations.CreateModel(
            name='UserTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500, verbose_name='enlace')),
                ('label', models.CharField(blank=True, max_length=160, verbose_name='etiqueta')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='reports.usertask')),
            ],
            options={
                'verbose_name': 'Enlace de tarea',
                'verbose_name_plural': 'Enlaces de tareas',
                'ordering': ['created_at'],
            },
        ),
    ]
