# Generated by Django 6.0.4 on 2026-05-07 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_usertask_links_alter_usertask_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaliCommunityWebcamMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField()),
                ('new_subscribers', models.PositiveIntegerField(default=0)),
                ('subscribers', models.PositiveIntegerField(default=0)),
                ('story_screenshot', models.FileField(blank=True, upload_to='bali_community_webcam/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bali_community_webcam_metrics', to='reports.businessunit')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bali_community_webcam_metrics', to='reports.country')),
            ],
            options={
                'verbose_name': 'Comunidad Webcam Bali',
                'verbose_name_plural': 'Comunidad Webcam Bali',
                'ordering': ['-metric_date'],
                'indexes': [models.Index(fields=['metric_date', 'business_unit', 'country'], name='reports_bali_comm_d_bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_unit', 'country', 'metric_date'), name='reports_bali_community_unique'), models.CheckConstraint(condition=models.Q(('new_subscribers__gte', 0)), name='reports_bali_community_new_nonnegative'), models.CheckConstraint(condition=models.Q(('subscribers__gte', 0)), name='reports_bali_community_total_nonnegative')],
            },
        ),
    ]
