# Generated by Django 6.0.4 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0041_default_user_task_due_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balidailymetric",
            old_name="visits",
            new_name="sessions",
        ),
        migrations.RemoveConstraint(
            model_name="balidailymetric",
            name="reports_bali_daily_visits_nonnegative",
        ),
        migrations.AddConstraint(
            model_name="balidailymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(sessions__gte=0),
                name="reports_bali_daily_sessions_nonnegative",
            ),
        ),
    ]
