# Generated by Django 6.0.6 on 2026-06-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0047_uva_ecuador_fixed_fx_and_cubrepezones_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('country_label', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('platform', models.CharField(choices=[('wordpress', 'WordPress'), ('shopify', 'Shopify'), ('custom', 'Custom'), ('unknown', 'Desconocido')], default='unknown', max_length=24)),
                ('stage', models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendiente'), ('paused', 'Pausada')], default='active', max_length=20)),
                ('logo', models.FileField(blank=True, upload_to='website_logos/')),
                ('monitor_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='reports.businessunit')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
                'ordering': ['display_order', 'name', 'country_label'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField()),
                ('overall_status', models.CharField(choices=[('healthy', 'Saludable'), ('warning', 'Alerta'), ('critical', 'Critica'), ('unknown', 'Sin dato')], default='unknown', max_length=20)),
                ('availability_status', models.CharField(choices=[('online', 'Online'), ('redirect', 'Redireccion'), ('offline', 'Offline'), ('error', 'Error'), ('unknown', 'Sin dato')], default='unknown', max_length=20)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, max_length=1000)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('platform_detected', models.CharField(blank=True, max_length=40)),
                ('is_https', models.BooleanField(default=False)),
                ('ssl_valid', models.BooleanField(blank=True, null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_days_remaining', models.IntegerField(blank=True, null=True)),
                ('security_headers_score', models.PositiveSmallIntegerField(default=0)),
                ('security_headers_total', models.PositiveSmallIntegerField(default=0)),
                ('missing_security_headers', models.JSONField(blank=True, default=list)),
                ('products_visible_status', models.CharField(default='unknown', max_length=24)),
                ('products_visible_count', models.PositiveIntegerField(blank=True, null=True)),
                ('products_in_stock_count', models.PositiveIntegerField(blank=True, null=True)),
                ('products_out_of_stock_count', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='reports.website')),
            ],
            options={
                'verbose_name': 'Chequeo de web',
                'verbose_name_plural': 'Chequeos de webs',
                'ordering': ['-checked_at', 'website__display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['stage', 'monitor_enabled'], name='reports_website_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='websitehealthcheck',
            index=models.Index(fields=['website', '-checked_at'], name='reports_webcheck_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='websitehealthcheck',
            index=models.Index(fields=['overall_status', 'checked_at'], name='reports_webcheck_status_idx'),
        ),
    ]
