# Generated by Django 6.0.6 on 2026-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0048_website_websitehealthcheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitehealthcheck',
            name='accessibility_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='best_practices_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='cumulative_layout_shift',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='first_contentful_paint_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='largest_contentful_paint_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='pagespeed_status',
            field=models.CharField(default='unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='performance_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='seo_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='speed_index_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitehealthcheck',
            name='total_blocking_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
