# Generated by Django 6.0.6 on 2026-07-08 19:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_marketplaceproductinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGeoAdMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField()),
                ('geo_level', models.CharField(choices=[('country', 'Pais'), ('region', 'Region'), ('city', 'Ciudad')], default='region', max_length=20)),
                ('location_key', models.SlugField(max_length=140)),
                ('location_name', models.CharField(max_length=160)),
                ('platform_location_id', models.CharField(blank=True, max_length=120)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('reach', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('purchases', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('spend_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Importado')], default='imported', max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Metrica geografica de pauta',
                'verbose_name_plural': 'Metricas geograficas de pauta',
                'ordering': ['-metric_date', 'business_unit__display_order', 'country__display_order', 'ad_platform__name', 'geo_level', 'location_name'],
            },
        ),
        migrations.AddField(
            model_name='dailygeoadmetric',
            name='ad_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_geo_metrics', to='reports.adplatform'),
        ),
        migrations.AddField(
            model_name='dailygeoadmetric',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_geo_ad_metrics', to='reports.businessunit'),
        ),
        migrations.AddField(
            model_name='dailygeoadmetric',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_geo_ad_metrics', to='reports.country'),
        ),
        migrations.AddIndex(
            model_name='dailygeoadmetric',
            index=models.Index(fields=['metric_date', 'business_unit', 'country', 'ad_platform'], name='reports_geo_date_dims_idx'),
        ),
        migrations.AddIndex(
            model_name='dailygeoadmetric',
            index=models.Index(fields=['country', 'geo_level', 'location_key'], name='reports_geo_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailygeoadmetric',
            constraint=models.UniqueConstraint(fields=('business_unit', 'country', 'ad_platform', 'metric_date', 'geo_level', 'location_key'), name='reports_geo_metric_unique'),
        ),
    ]
