# Generated by Django 6.0.4 on 2026-07-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0053_create_cache_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketplaceproductinventory',
            new_name='reports_mar_marketp_12f6f5_idx',
            old_name='reports_mar_market_6af5b1_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceproductinventory',
            new_name='reports_mar_marketp_8710d2_idx',
            old_name='reports_mar_market_74f5d8_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceproductinventory',
            new_name='reports_mar_marketp_0b96b9_idx',
            old_name='reports_mar_market_3e6db9_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceproductinventory',
            new_name='reports_mar_last_sy_d2f7b7_idx',
            old_name='reports_mar_last_sy_4ed0a6_idx',
        ),
    ]
