# Generated by Django 6.0.6 on 2026-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0056_distrisex_business_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(help_text='Fuente o job: woocommerce_co, google_ads_distrisex, websites_health...', max_length=80)),
                ('command', models.CharField(blank=True, help_text='Comando de management que la ejecuto.', max_length=120)),
                ('target_date', models.DateField(blank=True, help_text='Fecha de negocio procesada, no la de ejecucion.', null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('success', 'Exito'), ('failed', 'Fallo'), ('skipped', 'Omitida')], default='running', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Ejecucion de integracion',
                'verbose_name_plural': 'Ejecuciones de integraciones',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='reports_integrationrun_src_idx'), models.Index(fields=['status', '-started_at'], name='reports_integrationrun_st_idx')],
            },
        ),
    ]
