# Generated by Django 6.0.6 on 2026-08-03 19:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0059_limpieza_pruebas_y_marca_vacia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, help_text='Sesion del navegador que la inicio.', max_length=64)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversacion IA',
                'verbose_name_plural': 'Conversaciones IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'Sistema'), ('user', 'Usuario'), ('assistant', 'IA'), ('tool', 'Herramienta')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports.aiconversation')),
            ],
            options={
                'verbose_name': 'Mensaje IA',
                'verbose_name_plural': 'Mensajes IA',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', '-updated_at'], name='reports_aiconv_user_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='reports_aimsg_conv_idx'),
        ),
    ]
