# Generated by Django 6.0.6 on 2026-08-03 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0060_ai_conversations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='distilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='summarized_until',
            field=models.PositiveIntegerField(default=0, help_text='Id del ultimo mensaje que ya entro en el resumen.'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='summary',
            field=models.TextField(blank=True, help_text='Resumen de los turnos viejos. Se manda en vez de la historia completa.'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('', 'Sin calificar'), ('up', 'Sirvio'), ('down', 'No sirvio')], default='', max_length=8),
        ),
        migrations.CreateModel(
            name='AiMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('preference', 'Preferencia de trabajo'), ('style', 'Forma de comunicarse'), ('context', 'Contexto de la operacion'), ('decision', 'Decision tomada')], default='context', max_length=16)),
                ('origin', models.CharField(choices=[('distilled', 'Deducida de una conversacion'), ('explicit', 'El usuario pidio recordarla')], default='distilled', max_length=16)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='reports.aiconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memoria IA',
                'verbose_name_plural': 'Memorias IA',
                'ordering': ['-last_used_at', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='reports_aimem_user_idx')],
            },
        ),
    ]
