# Generated by Django 6.0.6 on 2026-08-03 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0062_pg_trgm_para_memorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='ai_attachments/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='reports.aiconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo IA',
                'verbose_name_plural': 'Archivos IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='reports_aiatt_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'sha256'), name='reports_aiattachment_user_hash_unique')],
            },
        ),
    ]
