# Generated by Django 6.0.6 on 2026-08-04 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0063_ai_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConfigChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(max_length=40)),
                ('object_label', models.CharField(max_length=160)),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.CharField(max_length=200)),
                ('new_value', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de configuracion IA',
                'verbose_name_plural': 'Cambios de configuracion IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target', '-created_at'], name='reports_aicfg_target_idx')],
            },
        ),
    ]
